Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,19 +1,34 @@
-name: Act on release created
+name: Enforce Jira ID in PR
 
 on:
-  release:
-    types: [created]
+  pull_request:
+    types:
+      - opened
+      - synchronize
+      - reopened
 
 jobs:
-  build:
-    name: Build
-    environment: dev_environment
+  enforce-jira-id:
     runs-on: ubuntu-latest
+  
+
     steps:
-      - uses: actions/checkout@v2
-      - name: Set env
-        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
-      - name: Test
+
+      - name: Install jq
+        run: sudo apt-get install jq
+      
+      - name: Check for Jira ID in PR title
         run: |
-          echo $RELEASE_VERSION
-          echo ${{ env.RELEASE_VERSION }}
+          PR_TITLE=$(curl -s -H "Authorization: Bearer ${{GITHUB_TOKEN}}" -H "Accept: application/vnd.github.v3+json" \"https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.title')
+          if [[ ! $PR_TITLE =~ [A-Z]+-[0-9]+ ]]; then
+            echo "Error: Jira issue key is missing in the PR title."
+            exit 1
+          fi
+
+      - name: Check for Jira ID in PR body
+        run: |
+          PR_BODY=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')
+          if [[ ! $PR_BODY =~ [A-Z]+-[0-9]+ ]]; then
+            echo "Error: Jira issue key is missing in the PR body."
+            exit 1
+          fi
